language: node_js
services:
- mongodb
node_js:
- '0.10'
env:
  global:
  - NODE_ENV: development
  - secure: F4MdsOdpcmyg0+U8x9OtiaBkrlv13KoeGjVUHPNbGcX7ErtOAyeY/srqpmJfrzF7zkNODOIX9z3oSyvVVkStQIwYpazNHWaPcPEHjJXrgRyEpI3pSdTEyIkmk+CAmrWrroyq0oMfd1v6OXTgtdtnxWEXqKMmfW0AOmFoGECINeI=
  - secure: DtlZVLZQOtDS5s6rO3vhiQcA5wxVnRnEQTgXKxSCTLGBjcesLTWv11Y84cdEY96bduaV2PHjJ4/9DbeVGPJGLu6Q16uHAHBSbpocHTLJq8iRNLkoje3Mk/Uce7NCRsSuLAGqY6AWokeS9C4PtnhzVSGWN4/MAJ1waNXz8QcdWlA=
  - secure: MxQNt3qPJyQkdCYv0g322SeBa+V49VCwIBin620pX+8BXMFcI4gMW33fuH+CAnaFlwAO869E2UvlBi0U0lSfAOFQP7CRBo7YsajDSqbXRQbQ/PbdDsU7C8ksi4iiSNSgWH/aRZiAYJ73h3QQv926Px7FTkoqN4DB6NULCWIzqfc=
  - secure: AyWg0aSLrmn8GbMeaenpBXI84AZgbo410pg++tlT1SpHjTjWpZ+7f6QCrjJOu/2EE5midiOktkNbFwJOu/Oef5ru3A9t+TORAOiHB2dHCnabiVgTfKVJJf1qnTDjapfY39UWV1/RQ9U8HEwa8EUzIF/Cw9xtMZTQ3RKs20oQ17A=
